Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2019-12, with the labels that each got.

#975 Work around unnecessary loss of precision for `FLOAT` conversions in MySQL 8.0.18
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
Labels: Area-MySQL, type-bug

#979 Override more tests that rely on implicit ordering behavior of SQL Server
  test/EFCore.MySql.FunctionalTests/Query/IncludeAsyncMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/IncludeMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/config.json.example
Labels: Area-EntityFramework, type-bug

#976 Update MySQL and MariaDB versions to their latest releases for CI
  azure-pipelines.yml
Labels: type-update

#980 Implement custom xUnit orderers
  test/EFCore.MySql.FunctionalTests/AssemblyInfo.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlTestCaseOrderer.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlTestCollectionOrderer.cs
Labels: type-enhancement

#981 Prepare codebase for .NET Standard 2.0
  Directory.Build.targets
  src/EFCore.MySql/Migrations/Internal/MySqlMigrator.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/Internal/MySqlRelationalConnection.cs
  src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
Labels: type-enhancement

#986 Upgrade to 3.1.0
  Directory.Build.props
  Pomelo.EntityFrameworkCore.MySql.sln
  azure-pipelines.yml
  eng/Development.props.sample
  eng/Versions.props
  global.json
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQueryTranslationPostprocessor.cs
  src/EFCore.MySql/Storage/Internal/MySqlDatabaseCreator.cs
  src/EFCore.MySql/Storage/ServerVersionSupport.cs
  test/Directory.Build.props
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/ConnectionSettingsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/CustomConvertersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/DataAnnotationMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/LazyLoadProxyMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySql55Test.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsWeakQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/DbFunctionsMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/DbFunctionsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/EscapesMySqlNoBackslashesTest.cs
  test/EFCore.MySql.FunctionalTests/Query/EscapesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/EscapesMySqlTestBase.cs
  test/EFCore.MySql.FunctionalTests/Query/FiltersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/FromSqlQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/FromSqlSprocQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/GearsOfWarQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/GroupByQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/IncludeAsyncMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/IncludeMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/QueryNavigationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/QueryNoClientEvalMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
  test/EFCore.MySql.IntegrationTests/EFCore.MySql.IntegrationTests.csproj
  test/EFCore.MySql.IntegrationTests/scripts/scaffold.sh
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
Labels: Area-EntityFramework, type-enhancement

#969 Ensure that generated GUIDs conform to the RFC 4122 standard.
  src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs
  src/EFCore.MySql/ValueGeneration/Internal/MySqlSequentialGuidValueGenerator.cs
  test/EFCore.MySql.Tests/ValueGeneration/Internal/MysqlSequentialGuidValueGeneratorTest.cs
Labels: type-bug

#987 TEXT, BLOB, GEOMETRY and JSON columns do not support default values
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
Labels: type-bug

#998 Implement support for MariaDB's specific default value syntax since 10.2.7
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
Labels: type-bug
