Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2020-11, with the labels that each got.

#1218 Check and reimplement nullability and argument null propagation for all SQL functions
  src/EFCore.MySql.Json.Microsoft/Extensions/MySqlJsonMicrosoftServiceCollectionExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftDomTranslator.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftMemberTranslatorPlugin.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftMethodCallTranslatorPlugin.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftPocoTranslator.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/MySqlJsonNewtonsoftServiceCollectionExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Query/Internal/MySqlJsonNewtonsoftDomTranslator.cs
  src/EFCore.MySql.Json.Newtonsoft/Query/Internal/MySqlJsonNewtonsoftMemberTranslatorPlugin.cs
  src/EFCore.MySql.Json.Newtonsoft/Query/Internal/MySqlJsonNewtonsoftMethodCallTranslatorPlugin.cs
  src/EFCore.MySql.Json.Newtonsoft/Query/Internal/MySqlJsonNewtonsoftPocoTranslator.cs
  src/EFCore.MySql.NTS/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlGeometryCollectionMemberTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlGeometryCollectionMethodTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlGeometryMemberTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlGeometryMethodTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlLineStringMemberTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlLineStringMethodTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlMultiLineStringMemberTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlNetTopologySuiteMemberTranslatorPlugin.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlNetTopologySuiteMethodCallTranslatorPlugin.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlPointMemberTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlPolygonMemberTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlPolygonMethodTranslator.cs
  src/EFCore.MySql/Extensions/MySqlJsonDbFunctionsExtensions.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlByteArrayMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonDbFunctionsTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonPocoTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitor.cs
  src/EFCore.MySql/Query/Internal/MySqlDateDiffFunctionsTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlDateTimeMemberTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlMathMethodTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlMethodCallTranslatorProvider.cs
  src/EFCore.MySql/Query/Internal/MySqlNewGuidTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlSqlExpressionFactory.cs
  src/EFCore.MySql/Query/Internal/MySqlStringMemberTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlTimeSpanMemberTranslator.cs
  src/Shared/Check.cs
  src/Shared/Statics.cs
Labels: type-enhancement

#1221 Upgrade to EF Core 5.0.0-rc.2.
  eng/Versions.props
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
  src/EFCore.MySql.Json.Newtonsoft/EFCore.MySql.Json.Newtonsoft.csproj
  src/EFCore.MySql.NTS/EFCore.MySql.NTS.csproj
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/DataAnnotationMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/StoreGeneratedMySqlTest.cs
Labels: type-enhancement

#1209 Update client evaluation handling of DbFunction extensions (EF.Functions) for EF Core 5.0
  src/EFCore.MySql.NTS/Extensions/MySqlNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.MySql.NTS/Extensions/MySqlSpatialDbFunctionsExtensions.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlNetTopologySuiteEvaluatableExpressionFilter.cs
  src/EFCore.MySql/Extensions/MySqlDbFunctionsExtensions.cs
  src/EFCore.MySql/Extensions/MySqlJsonDbFunctionsExtensions.cs
  src/EFCore.MySql/Query/Internal/IMySqlEvaluatableExpressionFilter.cs
  src/EFCore.MySql/Query/Internal/MySqlEvaluatableExpressionFilter.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonStringQueryTestBase.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindDbFunctionsQueryMySqlTest.MySql.cs
Labels: type-cleanup

#1222 Increase `max_connections` allowed for MySQL/MariaDB in CI
  azure-pipelines.yml
  src/EFCore.MySql/Storage/Internal/MySqlTransientExceptionDetector.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/TestMySqlRetryingExecutionStrategy.cs
Labels: type-bug

#1223 Update CI versions to use .NET 5 RC2
  .config/dotnet-tools.json
  azure-pipelines.yml
  global.json
Labels: type-cleanup

#854 Enable source link support
  azure-pipelines.yml
  eng/Versions.props
  src/Directory.Build.props
Labels: type-enhancement

#1225 Fix pack task for CI
  azure-pipelines.yml
Labels: type-bug

#1227 Fix typo in Versions.props
  eng/Versions.props
Labels: type-bug

#1228 Fix Arcade remnants and feed
  Development.props.sample
  Directory.Build.props
  Directory.Build.targets
  Pomelo.EFCore.MySql.sln
  Versions.props
  azure-pipelines.yml
  src/Directory.Build.props
  src/EFCore.MySql/EFCore.MySql.csproj
  test/Directory.Build.props
  test/EFCore.MySql.IntegrationTests/EFCore.MySql.IntegrationTests.csproj
  test/EFCore.MySql.IntegrationTests/scripts/legacy.ps1
  test/EFCore.MySql.IntegrationTests/scripts/rebuild.ps1
  test/EFCore.MySql.IntegrationTests/scripts/scaffold.ps1
  test/EFCore.MySql.IntegrationTests/scripts/stress.ps1
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
Labels: type-cleanup

#1230 Test PR build.
  azure-pipelines.yml
Labels: type-cleanup

#1234 Skip Windows tests only under certain conditions
  azure-pipelines.yml
Labels: type-enhancement

#1232 Remove JsonObject<T> support
  Development.props.sample
  Versions.props
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Storage/Internal/MySqlLegacyJsonTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.IntegrationTests/AppDb.cs
  test/EFCore.MySql.IntegrationTests/EFCore.MySql.IntegrationTests.csproj
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/1.1.2/20170829174711_initial.Designer.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/1.1.2/20170829174711_initial.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/1.1.2/AppDbModelSnapshot.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/2.0.1/20180529213507_initial.Designer.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/2.0.1/20180529213507_initial.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/2.0.1/AppDbModelSnapshot.csbak
  test/EFCore.MySql.IntegrationTests/Models/DataTypes.cs
  test/EFCore.MySql.IntegrationTests/Models/GeneratedTypes.cs
  test/EFCore.MySql.IntegrationTests/Startup.cs
  test/EFCore.MySql.IntegrationTests/Tests/Models/DataTypesTest.cs
  test/EFCore.MySql.IntegrationTests/Tests/Models/GeneratedTypesTest.cs
  test/EFCore.MySql.IntegrationTests/scripts/legacy.ps1
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
  test/EFCore.MySql.Tests/Migrations/ModelDifferMySqlTest.cs
  test/EFCore.MySql.Tests/Migrations/ModelSnapshotMySqlTest.cs
Labels: breaking-change, type-cleanup

#1235 Fix TimeSpan value translation of milliseconds
  src/EFCore.MySql/Storage/Internal/MySqlTimeSpanTypeMapping.cs
Labels: type-bug

#1019 Reenable tests, because upstream issues got fixed
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/CustomConvertersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/LazyLoadProxyMySqlTest.cs
Labels: type-cleanup

#1236 Backport: Fix TimeSpan value translation of milliseconds (#1235)
  src/EFCore.MySql/Storage/Internal/MySqlTimeSpanTypeMapping.cs
Labels: type-bug

#1237 Fix integration tests for MariaDB
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/1.1.2/20170829174711_initial.Designer.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/1.1.2/20170829174711_initial.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/1.1.2/AppDbModelSnapshot.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/2.0.1/20180529213507_initial.Designer.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/2.0.1/20180529213507_initial.csbak
  test/EFCore.MySql.IntegrationTests/LegacyMigrations/2.0.1/AppDbModelSnapshot.csbak
  test/EFCore.MySql.IntegrationTests/Models/GeneratedTypes.cs
  test/EFCore.MySql.IntegrationTests/scripts/legacy.ps1
Labels: type-cleanup

#1239 Make namespace adjustments
  src/EFCore.MySql/Extensions/MySqlPropertyBuilderExtensions.cs
  src/EFCore.MySql/Infrastructure/CharSet.cs
  src/EFCore.MySql/Infrastructure/MySqlCommonJsonChangeTrackingOptions.cs
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Infrastructure/MySqlDefaultDataTypeMappings.cs
  src/EFCore.MySql/Infrastructure/ServerVersion.cs
  src/EFCore.MySql/Query/MySqlJsonString.cs
  src/EFCore.MySql/Storage/Internal/MySqlRelationalConnection.cs
  test/EFCore.MySql.FunctionalTests/Storage/MySqlTypeMappingTest.cs
  test/EFCore.MySql.Tests/MySqlDbContextOptionsExtensionsTest.cs
Labels: type-cleanup

#1249 Fix handling of string version parameters
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersion.cs
  test/EFCore.MySql.Tests/MySqlDbContextOptionsExtensionsTest.cs
Labels: type-bug

#1251 Fix DELIMITER output for scripted migrations
  src/EFCore.MySql/Migrations/Internal/MySqlMigrator.cs
Labels: type-bug

#1253 Fix REPLACE() for charsets other than utf8mb4
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
Labels: Area-MariaDB, Area-MySQL, type-bug

#1254 Fix server version emit when scaffolding
  src/EFCore.MySql/Infrastructure/ServerVersion.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlCodeGenerationServerVersionCreationTypeMapping.cs
Labels: type-bug

#1259 Update .NET Core SDK and tools versions
  .config/dotnet-tools.json
  Pomelo.EntityFrameworkCore.MySql.sln
  global.json
Labels: type-cleanup

#1260 Add scaffolding support for computed columns, including STORED support
  src/EFCore.MySql/Extensions/StringExtensions.cs
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-bug

#1257 Add scaffolding support for computed columns
  src/EFCore.MySql/Extensions/StringExtensions.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-enhancement

#1195 Sequence sql generator
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
Labels: type-enhancement
