Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2020-09, with the labels that each got.

#1156 Add JSON support for MySQL and MariaDB for Microsoft's JSON package
  eng/Versions.props
  src/EFCore.MySql.NTS/EFCore.MySql.NTS.csproj
  src/EFCore.MySql/Design/Internal/MySqlJsonDesignTimeServices.cs
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Extensions/IEnumerableExtensions.cs
  src/EFCore.MySql/Extensions/MethodInfoExtensions.cs
  src/EFCore.MySql/Extensions/MySqlJsonDbContextOptionsBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlJsonDbFunctionsExtensions.cs
  src/EFCore.MySql/Extensions/MySqlJsonServiceCollectionExtensions.cs
  src/EFCore.MySql/Extensions/TypeExtensions.cs
  src/EFCore.MySql/IMySqlJsonSerializer.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlJsonOptionsExtension.cs
  src/EFCore.MySql/Metadata/MySqlValueGenerationStrategy.cs
  src/EFCore.MySql/Properties/MySqlJsonStrings.Designer.cs
  src/EFCore.MySql/Properties/MySqlJsonStrings.Designer.tt
  src/EFCore.MySql/Properties/MySqlJsonStrings.resx
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlArrayTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonDbFunctionsTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonDomTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonPocoTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlJsonParameterExpressionVisitor.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGeneratorFactory.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQueryTranslationPostprocessor.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQueryTranslationPostprocessorFactory.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitor.cs
  src/EFCore.MySql/Query/Expressions/Internal/MySqlJsonArrayIndexExpression.cs
  src/EFCore.MySql/Query/Expressions/Internal/MySqlJsonTraversalExpression.cs
  src/EFCore.MySql/Query/Internal/MySqlJsonMemberTranslatorPlugin.cs
  src/EFCore.MySql/Query/Internal/MySqlJsonMethodCallTranslatorPlugin.cs
  src/EFCore.MySql/Query/Internal/MySqlMemberTranslatorProvider.cs
  src/EFCore.MySql/Query/Internal/MySqlMethodCallTranslatorProvider.cs
  src/EFCore.MySql/Query/Internal/MySqlSqlExpressionFactory.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlJsonCodeGeneratorPlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlLegacyJsonTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonDocumentValueConverter.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonElementValueConverter.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonPocoValueConverter.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonStringValueConverter.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/Query/CompiledQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonDomQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonPocoQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonStringQueryTest.cs
Labels: type-enhancement

#1157 Decouple and refactor Microsoft JSON code into its own project and package
  Pomelo.EntityFrameworkCore.MySql.sln
  azure-pipelines.yml
  eng/Versions.props
  src/EFCore.MySql.Json.Microsoft/Design/Internal/MySqlJsonMicrosoftDesignTimeServices.cs
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
  src/EFCore.MySql.Json.Microsoft/Extensions/MySqlJsonMicrosoftDbContextOptionsBuilderExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Extensions/MySqlJsonMicrosoftServiceCollectionExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Infrastructure/Internal/MySqlJsonMicrosoftOptionsExtension.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftDomTranslator.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftMemberTranslatorPlugin.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftMethodCallTranslatorPlugin.cs
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftPocoTranslator.cs
  src/EFCore.MySql.Json.Microsoft/Scaffolding/Internal/MySqlJsonMicrosoftCodeGeneratorPlugin.cs
  src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMapping.cs
  src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMappingSourcePlugin.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/JsonDocumentValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/JsonElementValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/JsonPocoValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/JsonStringValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/build/netstandard2.0/Pomelo.EntityFrameworkCore.MySql.Json.Microsoft.targets
  src/EFCore.MySql.NTS/Extensions/MySqlNetTopologySuiteDbContextOptionsBuilderExtensions.cs
  src/EFCore.MySql.NTS/build/netstandard2.0/Pomelo.EntityFrameworkCore.MySql.NetTopologySuite.targets
  src/EFCore.MySql/Design/Internal/MySqlJsonDesignTimeServices.cs
  src/EFCore.MySql/Extensions/MySqlJsonDbFunctionsExtensions.cs
  src/EFCore.MySql/Extensions/MySqlJsonServiceCollectionExtensions.cs
  src/EFCore.MySql/IMySqlJsonSerializer.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlJsonOptionsExtension.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlConventionSetBuilder.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlValueGenerationStrategyConvention.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/IMySqlJsonPocoTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonPocoTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitor.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitorFactory.cs
  src/EFCore.MySql/Query/Internal/MySqlMemberTranslatorProvider.cs
  src/EFCore.MySql/Query/Internal/MySqlMethodCallTranslatorProvider.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlJsonCodeGeneratorPlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonDocumentValueConverter.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonPocoValueConverter.cs
  src/EFCore.MySql/Storage/ValueConversion/Internal/JsonStringValueConverter.cs
  src/Shared/MethodInfoExtensions.cs
  src/Shared/SharedTypeExtensions.cs
  src/Shared/TypeExtensions.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftDomQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftPocoQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftStringQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonPocoQueryTestBase.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonStringQueryTestBase.cs
Labels: type-enhancement

#1075 An item with the same key has already been added. Key: Microsoft.Enti…
  src/EFCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs
  test/EFCore.MySql.Tests/MySqlDbContextOptionsExtensionsTest.cs
Labels: type-bug

#1159 Implement change tracking support for JSON mapped properties
  src/EFCore.MySql.Json.Microsoft/Extensions/Internal/MySqlJsonMicrosoftPropertyBuilderExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Extensions/Internal/MySqlJsonMicrosoftPropertyExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Extensions/MySqlJsonMicrosoftDbContextOptionsBuilderExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Extensions/MySqlJsonMicrosoftPropertyBuilderExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Extensions/MySqlJsonMicrosoftPropertyExtensions.cs
  src/EFCore.MySql.Json.Microsoft/Infrastructure/Internal/MySqlJsonMicrosoftOptionsExtension.cs
  src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMapping.cs
  src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMappingSourcePlugin.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueComparison/Internal/MySqlJsonMicrosoftValueComparer.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftJsonDocumentValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftJsonElementValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftPocoValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftStringValueConverter.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/Internal/MySqlJsonNewtonsoftPropertyBuilderExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/Internal/MySqlJsonNewtonsoftPropertyExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/MySqlJsonNewtonsoftDbContextOptionsBuilderExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/MySqlJsonNewtonsoftPropertyBuilderExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/MySqlJsonNewtonsoftPropertyExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Extensions/MySqlJsonNewtonsoftServiceCollectionExtensions.cs
  src/EFCore.MySql.Json.Newtonsoft/Infrastructure/Internal/MySqlJsonNewtonsoftOptionsExtension.cs
  src/EFCore.MySql.Json.Newtonsoft/Query/Internal/MySqlJsonNewtonsoftPocoTranslator.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/Internal/MySqlJsonNewtonsoftTypeMapping.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/Internal/MySqlJsonNewtonsoftTypeMappingSourcePlugin.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/ValueComparison/Internal/MySqlJsonNewtonsoftValueComparer.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/ValueConversion/Internal/MySqlJsonNewtonsoftJTokenValueConverter.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/ValueConversion/Internal/MySqlJsonNewtonsoftPocoValueConverter.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/ValueConversion/Internal/MySqlJsonNewtonsoftStringValueConverter.cs
  src/EFCore.MySql/Extensions/MySqlCommonJsonChangeTrackingOptionsExtensions.cs
  src/EFCore.MySql/Infrastructure/Internal/IMySqlOptions.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlJsonOptionsExtension.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlOptionsExtension.cs
  src/EFCore.MySql/Internal/MySqlOptions.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonChangeTrackingOptions.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  src/EFCore.MySql/Storage/MySqlCommonJsonChangeTrackingOptions.cs
  src/EFCore.MySql/Storage/ValueComparison/Internal/IMySqlJsonValueComparer.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftDomChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftPocoChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftStringChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftDomChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftPocoChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftStringChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonPocoChangeTrackingTestBase.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonPocoQueryTestBase.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonStringChangeTrackingTestBase.cs
  test/EFCore.MySql.FunctionalTests/ServiceProviderPerContextFixtureBase.cs
Labels: type-enhancement

#1118 Add support for AUTO_INCREMENT in conjunction with value converters
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Properties/MySqlStrings.Designer.cs
  src/EFCore.MySql/Properties/MySqlStrings.resx
  src/EFCore.MySql/Strings.Designer.cs
  src/EFCore.MySql/Strings.resx
Labels: closed-fixed, type-bug

#1165 Fix index scaffolding issue
  azure-pipelines.yml
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
  src/EFCore.MySql.Json.Newtonsoft/EFCore.MySql.Json.Newtonsoft.csproj
  src/EFCore.MySql.NTS/EFCore.MySql.NTS.csproj
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlBoolOptimizingExpressionVisitor.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Query/BoolIndexingOptimizationDisabledMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
Labels: type-bug

#1169 Fix and extend spatial support
  src/EFCore.MySql.NTS/Extensions/MySqlSpatialDbFunctionsExtensions.cs
  src/EFCore.MySql.NTS/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlGeometryMethodTranslator.cs
  src/EFCore.MySql.NTS/Query/Internal/MySqlNetTopologySuiteMethodCallTranslatorPlugin.cs
  src/EFCore.MySql.NTS/Storage/Internal/MySqlGeographyWktWriter.cs
  src/EFCore.MySql.NTS/Storage/Internal/MySqlGeometryTypeMapping.cs
  src/EFCore.MySql.NTS/Storage/ValueConversion/Internal/GeometryValueConverter.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
  src/EFCore.MySql/Storage/ServerVersion.cs
  test/EFCore.MySql.FunctionalTests/Query/SpatialGeographyQueryMySqlTest.cs
Labels: type-bug, type-enhancement

#1171 Explicitly output `.ValueGeneratedNever()` for non-auto incrementing primary keys when scaffolding
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
Labels: type-bug

#1174 Fix (lon, lat) reordering across all supported database servers and versions
  src/EFCore.MySql.NTS/Storage/Internal/MySqlGeographyWktWriter.cs
  src/EFCore.MySql.NTS/Storage/Internal/MySqlGeometryTypeMapping.cs
  src/EFCore.MySql.NTS/Storage/Internal/MySqlNetTopologySuiteTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
Labels: type-bug
