Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2020-07, with the labels that each got.

#1114 Generate SRID restricted columns not just for GEOMETRY, but also for GEOMETRY derived types
  src/EFCore.MySql.NTS/Storage/Internal/MySqlNetTopologySuiteTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.MySql.cs
Labels: type-bug

#1115 Fix annotation related issue in SQL generation
  src/EFCore.MySql/Extensions/MySqlPropertyBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsAnnotationProvider.cs
Labels: type-bug

#1121 Add option to scaffold only tables (skipping views)
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/Internal/MySqlScaffoldingConnectionSettings.cs
Labels: type-enhancement

#1119 Implement HEX() and UNHEX() support as EF.Functions
  src/EFCore.MySql/Extensions/MySqlDbFunctionsExtensions.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Query/DbFunctionsMySqlTest.MySql.cs
Labels: type-enhancement

#1124 Add support for additional hex datatype translations.
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
Labels: type-enhancement

#1125 Add byte[], decimal, double and float data type support to HEX() client-side handling
  src/EFCore.MySql/Extensions/MySqlDbFunctionsExtensions.cs
Labels: type-bug

#1122 Fix CURRENT_TIMESTAMP discovery for MariaDB and for columns with precision when scaffolding
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
Labels: type-bug

#1123 Add SRID and prefix annotations only when necessary.
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
Labels: type-bug

#1126 Limit MySqlConnector to 0.x versions
  eng/Versions.props
Labels: type-update

#1127 Prepare release 3.1.2
  eng/Versions.props
Labels: type-update
