Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2020-04, with the labels that each got.

#1054 Update provider and tests to EF Core 3.1.3.
  Directory.Build.props
  eng/Versions.props
  global.json
  test/EFCore.MySql.FunctionalTests/DataAnnotationMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/PropertyEntryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/GearsOfWarQueryMySqlTest.cs
Labels: type-enhancement

#1057 Use database/table/column collation for default string method calls without `StringComparison` parameter
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Northwind.sql
  test/EFCore.MySql.FunctionalTests/Query/DbFunctionsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/EscapesMySqlNoBackslashesTest.cs
  test/EFCore.MySql.FunctionalTests/Query/EscapesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/FiltersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/FunkyDataQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/TestEnvironment.cs
Labels: type-bug

#1056 Match Expression for MySQL 5.6+ and MariaDB 10.3+
  src/EFCore.MySql/Extensions/MySqlDbFunctionsEnums.cs
  src/EFCore.MySql/Extensions/MySqlDbFunctionsExtensions.cs
  src/EFCore.MySql/Properties/MySqlStrings.Designer.cs
  src/EFCore.MySql/Properties/MySqlStrings.resx
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  src/EFCore.MySql/Query/Expressions/Internal/MySqlMatchExpression.cs
  src/EFCore.MySql/Query/Internal/MySqlSqlExpressionFactory.cs
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs
Labels: type-enhancement

#1062 Improve database information output and configuration in CI
  azure-pipelines.yml
Labels: type-enhancement

#1061 Extend upon new MATCH...AGAINST support
  src/EFCore.MySql/Extensions/MySqlDbFunctionsEnums.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  src/EFCore.MySql/Query/Expressions/Internal/MySqlMatchExpression.cs
  src/EFCore.MySql/Query/Internal/MySqlMethodCallTranslatorProvider.cs
  test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs
Labels: type-enhancement

#1063 Remove debugging output from yml
  azure-pipelines.yml
Labels: type-cleanup

#1069 Implement support for index/key prefix lengths
  src/EFCore.MySql/Extensions/MySqlIndexBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlIndexExtensions.cs
  src/EFCore.MySql/Extensions/MySqlKeyBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlKeyExtensions.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationNames.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/Internal/MySqlRelationalConnection.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  src/EFCore.MySql/Storage/ServerVersion.Support.cs
  src/EFCore.MySql/Storage/ServerVersion.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-enhancement
