Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2021-01, with the labels that each got.

#1284 Add translation support for String.Remove()
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindWhereQueryMySqlTest.cs
Labels: type-enhancement

#1294 Work around MySQL bug 96947
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlBug96947WorkaroundExpressionVisitor.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQueryTranslationPostprocessor.cs
  test/EFCore.MySql.FunctionalTests/Query/GearsOfWarQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/TPTGearsOfWarQueryMySqlTest.cs
Labels: Area-MySQL, external, type-bug

#1297 Improve test infrastructure
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/TestEnvironment.cs
  test/EFCore.MySql.Tests/.gitignore
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
  test/EFCore.MySql.Tests/MySqlTestFixtureBase.cs
  test/EFCore.MySql.Tests/TestWithFixture.cs
  test/EFCore.MySql.Tests/config.json.example
Labels: type-enhancement

#1298 Add test for MySQL bug 96947
  test/EFCore.MySql.Tests/Bugs/MySqlBug96947.cs
Labels: type-test

#1305 Fix issue regarding compound keys that also contain database generated columns other than auto_increment columns
  azure-pipelines.yml
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Update/Internal/MySqlUpdateSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/UpdatesMySqlFixture.cs
  test/EFCore.MySql.FunctionalTests/UpdatesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/test/EFCore.MySql.FunctionalTests/UpdatesMySqlTest.MySql.cs
Labels: type-bug

#1295 workaround/issue1293_extended
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlBug96947WorkaroundExpressionVisitor.cs
  test/EFCore.MySql.Tests/Bugs/MySqlBug96947.cs
  test/EFCore.MySql.Tests/MySqlTestFixtureBase.cs
  test/EFCore.MySql.Tests/TestWithFixture.cs
Labels: Area-MariaDB, external, type-bug

#1306 Fix issue regarding compound keys that also contain database generated columns other than auto_increment columns
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Update/Internal/MySqlUpdateSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/UpdatesMySqlFixture.cs
  test/EFCore.MySql.FunctionalTests/UpdatesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/test/EFCore.MySql.FunctionalTests/UpdatesMySqlTest.MySql.cs
Labels: type-bug

#1307 Fix collation usage
  src/EFCore.MySql/Extensions/MySqlPropertyBuilderExtensions.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
Labels: type-bug

#1311 Fix precedence issue when it comes to expressions like `boolParam = nullableBoolColumn IS NOT NULL`
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/Query/NullSemanticsQueryMySqlTest.cs
Labels: Area-EntityFramework, external, type-bug

#1312 Backport: Fix precedence issue when it comes to expressions like `boolParam = nullableBoolColumn IS NOT NULL`
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/PropertyEntryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NullSemanticsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.cs
Labels: Area-EntityFramework, external, type-bug
