Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2021-04, with the labels that each got.

#1364 Fix #1352 InvalidOperationException when scaffolding without including referenced table
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-bug

#1244 Remove CharSetBehavior
  src/EFCore.MySql/Infrastructure/CharSetAppendBehavior.cs
  src/EFCore.MySql/Infrastructure/Internal/IMySqlOptions.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlOptionsExtension.cs
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Infrastructure/ServerVersion.cs
  src/EFCore.MySql/Internal/MySqlOptions.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Query/Internal/MySqlCompiledQueryCacheKeyGenerator.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.FunctionalTests/ConferencePlannerMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/CustomConvertersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/DataAnnotationMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
  test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestHelpers.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
  test/EFCore.MySql.IntegrationTests/Startup.cs
  test/EFCore.MySql.Tests/MySqlOptionsExtensionTest.cs
Labels: type-cleanup

#1372 Simplify dependency version management and restrict EF Core versions
  Dependencies.targets
  Directory.Build.targets
  Pomelo.EFCore.MySql.sln
  Versions.props
  dotnet-tools.json
  global.json
  src/Directory.Build.props
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
  src/EFCore.MySql.Json.Newtonsoft/EFCore.MySql.Json.Newtonsoft.csproj
  src/EFCore.MySql.NTS/EFCore.MySql.NTS.csproj
  src/EFCore.MySql/EFCore.MySql.csproj
  test/Directory.Build.props
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/F1MySqlFixture.cs
  test/EFCore.MySql.FunctionalTests/OptimisticConcurrencyMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.cs
  test/EFCore.MySql.IntegrationTests/EFCore.MySql.IntegrationTests.csproj
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
Labels: type-cleanup

#1373 Add full-text parser support
  src/EFCore.MySql/Extensions/MySqlIndexBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlIndexExtensions.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationNames.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/Internal/MySqlTransientExceptionDetector.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-enhancement

#1380 feat: make MySqlSqlNullabilityProcessor in MySqlParameterBasedSqlProcessor transient
  src/EFCore.MySql/Query/Internal/MySqlParameterBasedSqlProcessor.cs
Labels: type-bug

#1382 Remove Pomelo specific transactions
  src/EFCore.MySql/Extensions/MySqlServiceCollectionExtensions.cs
  src/EFCore.MySql/Storage/Internal/MySqlRelationalTransaction.cs
  src/EFCore.MySql/Storage/Internal/MySqlRelationalTransactionFactory.cs
Labels: type-cleanup

#1386 Publish XML documentation
  src/Directory.Build.props
  src/EFCore.MySql.NTS/Query/Internal/MySqlNetTopologySuiteMemberTranslatorPlugin.cs
  src/EFCore.MySql/Diagnostics/MySqlEventId.cs
  src/EFCore.MySql/Extensions/MySqlModelExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlValueGenerationConvention.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Query/Internal/MySqlCompiledQueryCacheKeyGenerator.cs
  src/EFCore.MySql/Query/Internal/MySqlJsonMemberTranslatorPlugin.cs
  src/EFCore.MySql/Query/Internal/MySqlJsonMethodCallTranslatorPlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlDatabaseCreator.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMapping.cs
  src/EFCore.MySql/Storage/MySqlCommonJsonChangeTrackingOptions.cs
  src/EFCore.MySql/Update/Internal/MySqlModificationCommandBatchFactory.cs
  src/EFCore.MySql/Update/Internal/MySqlUpdateSqlGenerator.cs
  src/EFCore.MySql/ValueGeneration/Internal/MySqlValueGeneratorSelector.cs
Labels: type-enhancement

#1366 Fix MySQL json datatype charset and collation
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
Labels: type-bug

#1385 Expand character set and collation support
  Dependencies.targets
  Directory.Build.props
  Pomelo.EFCore.MySql.sln
  README.md
  Version.props
  dotnet-tools.json
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
  src/EFCore.MySql/Extensions/IEnumerableExtensions.cs
  src/EFCore.MySql/Extensions/MySqlEntityTypeBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlEntityTypeExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Infrastructure/Internal/IMySqlOptions.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlOptionsExtension.cs
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Internal/MySqlOptions.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationNames.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Migrations/Operations/MySqlCreateDatabaseOperation.cs
  src/EFCore.MySql/Query/Internal/MySqlCompiledQueryCacheKeyGenerator.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Storage/Internal/MySqlDatabaseCreator.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/CustomConvertersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/MigrationsInfrastructureMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
  test/EFCore.MySql.FunctionalTests/Query/CaseSensitiveNorthwindQueryMySqlFixture.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindDbFunctionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlNorthwindTestStoreFactory.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStoreFactory.cs
  test/EFCore.MySql.Tests/MySqlOptionsExtensionTest.cs
Labels: breaking-change, type-cleanup, type-enhancement

#1389 Improve scaffolding of JSON columns from MariaDB databases
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-enhancement

#1395 Fix syntax of code generated HasCharSet() and HasCollation() calls
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
Labels: type-bug

#1396 Move public Fluent API extension methods to the Microsoft.EntityFrameworkCore namespace
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
  src/EFCore.MySql/Extensions/MySqlIndexBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlIndexExtensions.cs
  src/EFCore.MySql/Extensions/MySqlKeyBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlKeyExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlValueGenerationConvention.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Storage/Internal/MySqlDatabaseCreator.cs
  src/EFCore.MySql/Update/Internal/MySqlUpdateSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
Labels: breaking-change, type-bug

#1398 Add scaffolding support for MySQL 8.0.13+ style default value expressions
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-enhancement

#1391 Make string method translations, that contain a StringComparison parameter, opt-in
  src/EFCore.MySql/Infrastructure/Internal/IMySqlOptions.cs
  src/EFCore.MySql/Infrastructure/Internal/MySqlOptionsExtension.cs
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Internal/MySqlOptions.cs
  src/EFCore.MySql/Properties/MySqlStrings.Designer.cs
  src/EFCore.MySql/Properties/MySqlStrings.resx
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitor.cs
  src/EFCore.MySql/Query/Internal/MySqlMethodCallTranslatorProvider.cs
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Query/CaseSensitiveNorthwindQueryMySqlFixture.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindMiscellaneousQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindWhereQueryMySqlTest.cs
Labels: breaking-change, type-cleanup, type-enhancement

#1392 Improve XML documentation of ServerVersion and derived classes and rename methods
  src/EFCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlCodeGenerationServerVersionCreationTypeMapping.cs
  test/EFCore.MySql.FunctionalTests/ConnectionSettingsMySqlTest.cs
  test/EFCore.MySql.Tests/Bugs/MySqlBug96947.cs
  test/EFCore.MySql.Tests/Migrations/ServerVersionTest.cs
  test/EFCore.MySql.Tests/MySqlDbContextOptionsExtensionsTest.cs
  test/Shared/AppConfig.cs
Labels: breaking-change, type-cleanup, type-enhancement

#1399 Setup Fluent API, to generate client-side sequential Guids for appropriate primary key columns, when scaffolding
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/ValueGeneration/Internal/MySqlSequentialGuidValueGenerator.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlDatabaseCleaner.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlDatabaseFacadeTestExtensions.cs
Labels: type-enhancement

#1401 Ensure backward compatibility with MySQL 5.6
  src/EFCore.MySql/Extensions/DbDataReaderExtensions.cs
  src/EFCore.MySql/Extensions/DbDataRecordExtensions.cs
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Properties/AssemblyInfo.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  src/EFCore.MySql/Scaffolding/Internal/SqlDataReaderExtension.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.FunctionalTests/AssemblyInfo.cs
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MusicStoreMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
  test/EFCore.MySql.FunctionalTests/Query/BoolIndexingOptimizationDisabledMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/EscapesMySqlTestBase.cs
  test/EFCore.MySql.FunctionalTests/Query/GearsOfWarQueryMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftDomChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftDomQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftPocoChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftPocoQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftStringChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonMicrosoftStringQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftDomChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftDomQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftPocoChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftPocoQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftStringChangeTrackingTest.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonNewtonsoftStringQueryTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/SpatialQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
  test/EFCore.MySql.FunctionalTests/TableSplittingMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestHelpers.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestFrameworkDiscoverer.cs
Labels: type-enhancement

#1407 Implement support for value generation strategies, that don't use an enum value but its underlying value equivalent
  src/EFCore.MySql/Internal/MySqlValueGenerationStrategyCompatibility.cs
  src/EFCore.MySql/Metadata/Internal/EnumExtensions.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.MySql.cs
Labels: type-enhancement

#1405 Refine and improve charset and collation delegation support
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
  src/EFCore.MySql/Extensions/MySqlEntityTypeBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlEntityTypeExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelExtensions.cs
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Metadata/DelegationModes.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs
  src/Shared/Check.cs
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/CustomConvertersMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsInfrastructureMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-enhancement

#1404 Add optimized default collation for character based Guid storing columns
  src/EFCore.MySql/Extensions/MySqlModelBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelExtensions.cs
  src/EFCore.MySql/Infrastructure/Internal/IMySqlOptions.cs
  src/EFCore.MySql/Internal/MySqlOptions.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationNames.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Storage/Internal/MySqlGuidTypeMapping.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-enhancement

#1409 Fix leaking annotations and empty migration operations
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
Labels: type-bug

#1411 Ensure explicit charset/collation precedence over inherited collation/charset counterpart
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
  src/EFCore.MySql/Metadata/DelegationModes.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug, type-enhancement
