Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2021-11, with the labels that each got.

#1538 Remove explicit SupportedServerVersionCondition instances, that are now redundant due to MySqlXunitTestRunner
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsSharedTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/GearsOfWarQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ManyToManyNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ManyToManyQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindAggregateOperatorsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindAggregateQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindGroupByQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindIncludeNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindIncludeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindJoinQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindMiscellaneousQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindStringIncludeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/OwnedEntityQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/QueryNavigationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/TPTGearsOfWarQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/TPTManyToManyNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/TPTManyToManyQueryMySqlTest.cs
Labels: type-cleanup

#1549 Upgrade to EF Core 6.0.0-rc2
  Dependencies.targets
  dotnet-tools.json
  src/EFCore.MySql/Design/Internal/MySqlDesignTimeServices.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  src/EFCore.MySql/Scaffolding/Internal/FixedCSharpEntityTypeGenerator.cs
  src/EFCore.MySql/Storage/Internal/MySqlDatabaseCreator.cs
  test/EFCore.MySql.FunctionalTests/ConnectionSettingsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/DataAnnotationMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/GraphUpdatesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/ProxyGraphUpdatesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsSharedTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ManyToManyHeterogeneousQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindGroupByQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindIncludeNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/OwnedEntityQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/SimpleQueryMySqlTest.cs
  test/EFCore.MySql.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
Labels: type-update

#1550 Remove temporary workarounds
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  src/Shared/SharedTypeExtensions.cs
  test/EFCore.MySql.FunctionalTests/ConcurrencyDetectorDisabledMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/ConcurrencyDetectorEnabledMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/FromSqlQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindGroupByQueryMySqlTest.cs
Labels: type-cleanup

#1551 Fix another test with weird (nondeterministic?) MariaDB ordering behavior
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeQueryMySqlTest.cs
Labels: type-test

#1552 Fix another MySQL (on Windows) ordering test
  test/EFCore.MySql.FunctionalTests/Query/OwnedEntityQueryMySqlTest.cs
Labels: type-test

#1553 Skip NorthwindSplitIncludeQueryMySqlTest tests for MariaDB and MySQ < 8.0
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeQueryMySqlTest.cs
Labels: type-test

#1555 Upgrade to EF Core 6.0.0
  Dependencies.targets
  Version.props
  azure-pipelines.yml
  dotnet-tools.json
  global.json
Labels: type-update

#1556 Prepare 6.0.0 GA release
  Dependencies.targets
  src/EFCore.MySql/Storage/Internal/MySqlDateTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTimeTypeMapping.cs
Labels: type-cleanup

#1569 Fix column type recognition from non-lowercased type names
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug

#1570 [BACKPORT] Fix column type recognition from non-lowercased type names
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug

#1561 Update README.md
  README.md
Labels: type-cleanup
