Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2021-09, with the labels that each got.

#1475 Move migration script handling back to custom Migrator implementation
  src/EFCore.MySql/Extensions/MySqlServiceCollectionExtensions.cs
  src/EFCore.MySql/Migrations/Internal/MySqlHistoryRepository.cs
  src/EFCore.MySql/Migrations/Internal/MySqlMigrator.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/FullMigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/MigrationsInfrastructureMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestMigrator.cs
  test/EFCore.MySql.Tests/TestUtilities/FakeModificationCommand.cs
Labels: type-bug

#1497 Add translation of DateTime.AddMilliseconds
  src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs
  test/EFCore.MySql.IntegrationTests/Tests/Models/ExpressionTest.cs
Labels: type-enhancement

#1498 Add support for default value expression syntax
  src/EFCore.MySql/Diagnostics/Internal/MySqlLoggingDefinitions.cs
  src/EFCore.MySql/Diagnostics/MySqlEventId.cs
  src/EFCore.MySql/Internal/MySqlLoggerExtensions.cs
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Properties/MySqlStrings.Designer.cs
  src/EFCore.MySql/Properties/MySqlStrings.resx
  test/EFCore.MySql.FunctionalTests/DefaultValuesTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ManyToManyFieldsLoadMySqlTest.cs
Labels: type-enhancement

#1500 Add legacy support for specifying a character set as part of the store type/column type
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug

#1502 [BACKPORT] Add legacy support for specifying a character set as part of the store type/column type
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.FunctionalTests/BuiltInDataTypesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug

#1501 Upgrade to EF Core 6.0.0-preview6
  Dependencies.targets
  Directory.Build.props
  azure-pipelines.yml
  dotnet-tools.json
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Infrastructure/MySqlDefaultDataTypeMappings.cs
  src/EFCore.MySql/Internal/MySqlOptions.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitor.cs
  src/EFCore.MySql/Query/Internal/MySqlDateTimeMemberTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlMathMethodTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlSqlExpressionFactory.cs
  src/EFCore.MySql/Storage/Internal/MySqlDateTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTimeTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  src/Shared/SharedTypeExtensions.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/MySqlMigrationsSqlGeneratorTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.cs
  test/EFCore.MySql.IntegrationTests/EFCore.MySql.IntegrationTests.csproj
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
Labels: type-update

#1504 Fix typos
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
Labels: type-cleanup

#1517 Implement explicit code literal generation for DateOnly and TimeOnly as a workaround
  src/EFCore.MySql/Storage/Internal/MySqlDateTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTimeTypeMapping.cs
Labels: type-bug, Area-EntityFramework, external

#1507 Skip redundant AlterColumn call generation for migrations
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug

#1516 Remove forced COLLATE clause from string conversions
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/Query/CompositeKeysQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/CompositeKeysSplitQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.cs
  test/EFCore.MySql.Tests/Query/MySqlCollationTest.cs
Labels: type-enhancement, breaking-change

#1505 [BACKPORT] Fix typos
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
Labels: type-cleanup

#1518 Fix leaking delegation annotations in old objects of migration operations
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
Labels: type-bug

#1520 Improve readability of delegation algorithms and fix charset delegation edge case
  src/EFCore.MySql/Metadata/Internal/MySqlAnnotationProvider.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug, type-cleanup

#1522 [BACKPORT] Skip redundant AlterColumn call generation for migrations
  src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug
