Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2021-05, with the labels that each got.

#1422 Rename unsuitable file name to class name within the file.
  src/EFCore.MySql/Extensions/MySqlDbContextOptionsBuilderExtensions.cs
Labels: type-cleanup

#1424 Syntax correction in Readme example
  README.md
Labels: type-cleanup

#1428 Support MariaDB specific comments in column type when scaffolding
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-bug

#1430 Support MariaDB specific comments in column type when scaffolding
  src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs
  test/EFCore.MySql.FunctionalTests/Scaffolding/MySqlDatabaseModelFactoryTest.cs
Labels: type-bug

#1431 Reuse MySqlConnector's MySqlException.IsTransient implementation
  src/EFCore.MySql/Storage/Internal/MySqlTransientExceptionDetector.cs
Labels: type-cleanup

#1432 Fix and improve test framework
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestFrameworkDiscoverer.cs
  test/EFCore.MySql.Tests/AssemblyInfo.cs
  test/EFCore.MySql.Tests/MySqlTestFixtureBase.cs
  test/EFCore.MySql.Tests/TestWithFixture.cs
Labels: type-test

#1433 Add tests for x/y and longitude/latitude behavior in MySQL<8/MariaDB and MySQL 8+
  test/EFCore.MySql.Tests/Behaviors/MySql8WithSridConstraintSpatialBehavior.cs
  test/EFCore.MySql.Tests/Behaviors/MySql8WithoutSridConstraintSpatialBehavior.cs
  test/EFCore.MySql.Tests/Behaviors/SpatialBehavior.cs
Labels: type-test
