Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2022-05, with the labels that each got.

#1649 Fix JSON value projections, so they are cast to the expected type.
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonPocoTranslator.cs
  src/EFCore.MySql/Query/Expressions/Internal/MySqlJsonTraversalExpression.cs
  src/EFCore.MySql/Storage/Internal/IJsonSpecificTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlGuidTypeMapping.cs
  test/EFCore.MySql.FunctionalTests/Query/JsonPocoQueryTestBase.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStore.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStoreFactory.cs
Labels: type-bug

#1650 Fix issue, where changes to a connection string did not affect an internal master connection.
  src/EFCore.MySql/Storage/Internal/MySqlRelationalConnection.cs
  test/EFCore.MySql.FunctionalTests/ConnectionMySqlTest.cs
Labels: type-bug

#1645 Add support for `string.IndexOf(string value, int startIndex) `
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlStringMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.MySql.cs
Labels: type-enhancement

#1651 Disable TLS usage for local database server connections in CI test runs.
  test/EFCore.MySql.FunctionalTests/config.json.example
  test/EFCore.MySql.IntegrationTests/config.json.example
  test/EFCore.MySql.Tests/config.json.example
Labels: type-test

#1652 Optimize `string.IndexOf(string, int)` translation
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.MySql.cs
Labels: type-perf-improvement
