Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2022-07, with the labels that each got.

#1677 Fix interference of HAVING workaround with UNION ALL statements
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlHavingExpressionVisitor.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.MySql.cs
Labels: type-bug, backport-candidate

#1680 [BACKPORT] Fix interference of HAVING workaround with UNION ALL statements
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlHavingExpressionVisitor.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.MySql.cs
Labels: type-bug, backport

#1681 Let EF Core assign unique aliases for specific HAVING clauses
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlHavingExpressionVisitor.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSelectQueryMySqlTest.MySql.cs
Labels: type-cleanup

#1694 Fix ComplexNavigationsQueryMySqlTest.SelectMany_subquery_with_custom_projection test
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexNavigationsSharedTypeQueryMySqlTest.cs
Labels: type-test

#1693 Add support for AddMySql() method
  src/EFCore.MySql/Extensions/MySqlDbContextOptionsBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlServiceCollectionExtensions.cs
  src/EFCore.MySql/Storage/Internal/MySqlRelationalConnection.cs
  test/EFCore.MySql.Tests/MySqlDbContextOptionsExtensionsTest.cs
Labels: type-enhancement
