Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2023-10, with the labels that each got.

#1682 Change `Match` extension methods and introduce `IsMatch` ones
  src/EFCore.MySql/Extensions/MySqlDbFunctionsExtensions.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlDbFunctionsExtensionsMethodTranslator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlSqlTranslatingExpressionVisitor.cs
  src/EFCore.MySql/Query/Expressions/Internal/MySqlMatchExpression.cs
  src/EFCore.MySql/Query/Internal/MySqlSqlExpressionFactory.cs
  test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs
Labels: type-enhancement, breaking-change

#1698 Adjust syntax of log fragment
  src/EFCore.MySql/Infrastructure/Internal/MySqlOptionsExtension.cs
Labels: type-enhancement

#1795 Move CI from Azure DevOps (AZDO) to GitHub Actions
  .github/workflows/build.yml
  Dependencies.targets
  azure-pipelines.yml
  test/Directory.Build.props
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-enhancement

#1800 Upgrade to EF Core 8.0.0-rc.2
  .github/workflows/build.yml
  Dependencies.targets
  Directory.Build.props
  NuGet.config
  dotnet-tools.json
  global.json
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
  src/EFCore.MySql.Json.Newtonsoft/EFCore.MySql.Json.Newtonsoft.csproj
  src/EFCore.MySql.NTS/EFCore.MySql.NTS.csproj
  src/EFCore.MySql/EFCore.MySql.csproj
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/Query/ComplexTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindAggregateOperatorsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindAggregateQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/PrimitiveCollectionsQueryMySqlTest.cs
  test/EFCore.MySql.IntegrationTests/EFCore.MySql.IntegrationTests.csproj
  test/EFCore.MySql.Tests/EFCore.MySql.Tests.csproj
  test/EFCore.MySql.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
Labels: type-update
