Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2024-02, with the labels that each got.

#1839 Fix support for model compilation in regards to type mappings
  Dependencies.targets
  src/EFCore.MySql.Json.Microsoft/Query/Internal/MySqlJsonMicrosoftDomTranslator.cs
  src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMapping.cs
  src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMappingSourcePlugin.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftJsonDocumentValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftJsonElementValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftPocoValueConverter.cs
  src/EFCore.MySql.Json.Microsoft/Storage/ValueConversion/Internal/MySqlJsonMicrosoftStringValueConverter.cs
  src/EFCore.MySql.Json.Newtonsoft/Query/Internal/MySqlJsonNewtonsoftDomTranslator.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/Internal/MySqlJsonNewtonsoftTypeMapping.cs
  src/EFCore.MySql.Json.Newtonsoft/Storage/Internal/MySqlJsonNewtonsoftTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Design/Internal/MySqlCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.MySql/Design/Internal/MySqlDesignTimeServices.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlJsonPocoTranslator.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlCodeGenerationMemberAccessTypeMapping.cs
  src/EFCore.MySql/Scaffolding/Internal/MySqlCodeGenerationServerVersionCreationTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/IMySqlCSharpRuntimeAnnotationTypeMappingCodeGenerator.cs
  src/EFCore.MySql/Storage/Internal/MySqlBoolTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlByteArrayTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlDateTimeOffsetTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlDateTimeTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlDateTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlGuidTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTimeTypeMapping.cs
  src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs
  src/EFCore.MySql/Storage/Internal/MySqlYearTypeMapping.cs
Labels: type-bug

#1815 Bump mariadb releases + 11.2.2 now GA
  .github/workflows/build.yml
Labels: type-update

#1840 Prepare GA release `8.0.0`
  Dependencies.targets
  Version.props
  src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs
Labels: type-update

#1816 README supported MariaDB versions to correspond to CI
  README.md
Labels: type-update

#1843 Use `AutoEnlist=false` and `Pooling=false` in `AutoDetect()` calls
  src/EFCore.MySql/Infrastructure/ServerVersion.cs
Labels: type-enhancement

#1844 Merge ADD COLUMN/MODIFY COLUMN with AUTO_INCREMENT statement with ADD CONSTRAINT PRIMARY KEY statement where necessary, because MySQL requires an AUTO_INCREMENT column to be a key (and making it a key after column creation is already too late).
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-bug, backport-candidate

#1847 Refactor BytesToDateTimeConverter, so it works out-of-the-box with compiled models.
  src/EFCore.MySql/Storage/Internal/BytesToDateTimeConverter.cs
Labels: type-bug

#1848 Improve `QueryBaselineUpdater` to automatically update the correct main or customized file from a `QueryBaseline.txt` file.
  tools/QueryBaselineUpdater/Program.cs
  tools/QueryBaselineUpdater/QueryBaselineUpdater.csproj
Labels: type-enhancement

#1850 Workaround SELECT ... ORDER BY (SELECT 1) related bug in Oracle's MySQL implementation, that can lead to completely wrong data being returned.
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/ProxyGraphUpdatesMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindEFPropertyIncludeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/DebugServices/DebugRelationalCommand.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/DebugServices/DebugRelationalCommandBuilder.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/DebugServices/DebugRelationalCommandBuilderFactory.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/DebugServices/DebugRelationalDataReader.cs
Labels: type-bug, Area-MySQL, external

#1851 Support specific/custom test orders and a deterministic order in which test classes are executed.
  test/EFCore.MySql.FunctionalTests/AssemblyInfo.cs
  test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/IMySqlTestClassOrderer.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlTestCaseOrderer.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlTestCollectionOrderer.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestAssemblyRunner.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestCollectionRunner.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestFramework.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestFrameworkDiscoverer.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/Xunit/MySqlXunitTestFrameworkExecutor.cs
Labels: type-enhancement, type-test

#1852 Update to EF Core 8.0.1
  Dependencies.targets
  dotnet-tools.json
  src/EFCore.MySql.NTS/Query/Internal/MySqlGeometryMethodTranslator.cs
  src/EFCore.MySql.NTS/Storage/Internal/MySqlNetTopologySuiteTypeMappingSourcePlugin.cs
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
  src/EFCore.MySql/Design/Internal/MySqlCSharpRuntimeAnnotationCodeGenerator.cs
  src/EFCore.MySql/Extensions/MySqlEntityTypeExtensions.cs
  src/EFCore.MySql/Extensions/MySqlIndexExtensions.cs
  src/EFCore.MySql/Extensions/MySqlKeyExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlModelExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyBuilderExtensions.cs
  src/EFCore.MySql/Extensions/MySqlPropertyExtensions.cs
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlConventionSetBuilder.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlRuntimeModelConvention.cs
  src/EFCore.MySql/Metadata/Conventions/MySqlValueGenerationStrategyConvention.cs
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlParameterInliningExpressionVisitor.cs
  test/EFCore.MySql.FunctionalTests/BadDataJsonDeserializationMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/PrimitiveCollectionsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/TPCGearsOfWarQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlNorthwindTestStoreFactory.cs
  test/EFCore.MySql.FunctionalTests/TestUtilities/MySqlTestStoreFactory.cs
  test/EFCore.MySql.FunctionalTests/TransactionMySqlTest.cs
Labels: type-bug, type-enhancement, type-update

#1832 Allow ExceptIntercept, ExceptInterceptPrecedence for MySql versions >= 8.0.31
  src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs
Labels: type-enhancement

#1802 Add RenameIndex support for MariaDB versions >= 10.5.2
  src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs
Labels: type-enhancement
