Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2024-04, with the labels that each got.

#1906 Remove explicit reference to `System.Text.Json` package from `Pomelo.EntityFrameworkCore.MySql.Json.Microsoft` package
  Dependencies.targets
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
Labels: type-enhancement, backport-candidate

#1912 Fix test from "Swap parameters in `Math.Log(double a, double newBase)` translation"
  test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.MySql.cs
Labels: type-test

#1913 Fix regression bug to allow usage of named connection strings again
  src/EFCore.MySql/Internal/MySqlOptions.cs
  test/EFCore.MySql.Tests/MySqlRelationalConnectionTest.cs
Labels: type-bug, backport-candidate

#1872 Update integration tests README.md and remove obsolete files
  test/EFCore.MySql.IntegrationTests/README.md
  test/EFCore.MySql.IntegrationTests/scripts/stress.sh
Labels: type-cleanup, type-update
