Repository PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, pull requests merged in 2025-03, with the labels that each got.

#1977 [BACKPORT] Remove explicit reference to `System.Text.Json` package from `Pomelo.EntityFrameworkCore.MySql.Json.Microsoft` package
  Dependencies.targets
  src/EFCore.MySql.Json.Microsoft/EFCore.MySql.Json.Microsoft.csproj
Labels: type-bug, backport

#1978 [BACKPORT] Update CI and version handling to latest one from `main` branch
  .github/workflows/build.yml
  Version.props
Labels: type-enhancement, backport

#1979 Update dependencies and test suite (EF Core 8.0.13)
  Dependencies.targets
  dotnet-tools.json
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/AdHocAdvancedMappingsQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/AdHocComplexTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/ComplexTypeQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/PrimitiveCollectionsQueryMySqlTest.cs
Labels: type-update

#1980 Don't generate `DEFAULT 0` clause for `AUTO_INCREMENT` columns
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/FullMigrationsMySqlTest.cs
Labels: type-bug

#1981 [BACKPORT] Don't generate `DEFAULT 0` clause for `AUTO_INCREMENT` columns
  src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs
  test/EFCore.MySql.FunctionalTests/FullMigrationsMySqlTest.cs
Labels: type-bug, backport

#1983 Update issue templates.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type-meta

#1988 Fix issue where using `DateTime.UtcNow` and `DateTime.Now` will lose precision when used inside of a query
  src/EFCore.MySql/Query/Internal/MySqlDateTimeMemberTranslator.cs
  src/EFCore.MySql/Query/Internal/MySqlMemberTranslatorProvider.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindDbFunctionsQueryMySqlTest.MySql.cs
  test/EFCore.MySql.FunctionalTests/Query/NorthwindWhereQueryMySqlTest.cs
  test/EFCore.MySql.FunctionalTests/Query/TPCGearsOfWarQueryMySqlTest.cs
  test/EFCore.MySql.IntegrationTests/Tests/Models/ExpressionTest.cs
Labels: type-bug

#1984 Add HasCharSet method for ComplexPropertyBuilder
  src/EFCore.MySql/Design/Internal/MySqlAnnotationCodeGenerator.cs
  src/EFCore.MySql/Extensions/MySqlComplexTypePropertyBuilderExtensions.cs
  test/EFCore.MySql.FunctionalTests/MigrationsMySqlTest.cs
Labels: type-enhancement
